# -*- coding: utf-8 -*-
"""Statistics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uxi90zQ1z8AuVVWub01abiSIQkWvwYtf
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('Dane_nie_podzielone.csv', header=None, names=['name', 'all'])
df['len'] = df['name'].apply(lambda x: len(str(x)))

df2 = pd.read_csv('Dane_podzielone.csv')
df2['len'] = df2['name'].apply(lambda x: len(str(x)))

plt.figure(figsize=(15, 15))

plt.xlabel("Liczba liter")
plt.ylabel("Liczba wystąpień")

x = df['len']
y = df['all']
plt.scatter(x, y, marker = '.', color="blue", alpha=0.5, label="Pierwsza wersja")

x2 = df2['len']
y2 = df2['all']
plt.scatter(x2, y2, marker = '.', color="red", alpha=0.5, label="Druga wersja")

plt.legend()

plt.figure(figsize=(10, 10))
x = df2['len']
y = df2['all']
plt.scatter(x, y, marker = '.', color="red")

plt.figure(figsize=(10, 10))
x = df['len']
y = df['all']
plt.ylim([0, 5000])
plt.scatter(x, y, marker = '.')

df1 = df[['len', 'all']].groupby('len', as_index=False).count().astype('int')
x1 = df1['len']
y1 = df1['all']

df3 = df2[['len', 'all']].groupby('len', as_index=False).count().astype('int')
x2 = df3['len']
y2 = df3['all']

plt.figure(figsize=(10, 10))
plt.xlabel("Liczba liter")
plt.ylabel("Liczba różnych nazw")
plt.plot(x1, y1, 'b', label="Pierwsza wersja")
plt.plot(x2, y2, 'r', label="Druga wersja")
plt.legend()

df1 = df[['len', 'all']].groupby('len', as_index=False).mean().astype('int')
x1 = df1['len']
y1 = df1['all']

df3 = df2[['len', 'all']].groupby('len', as_index=False).mean().astype('int')
x2 = df3['len']
y2 = df3['all']

plt.figure(figsize=(10, 10))
plt.xlabel("Liczba liter")
plt.ylabel("Średnia liczba wystąpień")
plt.plot(x1, y1, 'b', label="Pierwsza wersja")
plt.plot(x2, y2, 'r', label="Druga wersja")
plt.legend()

df.sort_values("all", ascending=False).head(20)

df2.sort_values("all", ascending=False).head(20)

df4 = {}
x4 = {}
y4 = {}
plt.figure(figsize=(10, 10))
plt.xlabel("Liczba liter")
plt.ylabel("Liczba różnych nazw")

for name in ["all", "function", "class", "import", "exception", "param", "keyword", "alias", "none"]:
  df4[name] = df2[['len', name]].groupby('len', as_index=False).count().astype('int')
  x4[name] = df4[name]['len']
  y4[name] = df4[name][name]
  plt.plot(x4[name], y4[name], label=name)

plt.legend()



df4 = {}
x4 = {}
y4 = {}
plt.figure(figsize=(10, 10))
plt.xlabel("Liczba liter")
plt.ylabel("Liczba różnych nazw")

for name in ["all", "function", "class", "import", "exception", "param", "keyword", "alias", "none"]:
  df4[name] = df2[['len', name]].dropna().groupby('len', as_index=False).count().astype('int')
  x4[name] = df4[name]['len']
  y4[name] = df4[name][name]
  plt.plot(x4[name], y4[name], label=name)

plt.legend()

df4 = {}
x4 = {}
y4 = {}
plt.figure(figsize=(10, 10))
plt.xlabel("Liczba liter")
plt.ylabel("Średnia liczba wystąpień")

for name in ["all", "function", "class", "import", "exception", "param", "keyword", "alias", "none"]:
  df4[name] = df2[['len', name]].dropna().groupby('len', as_index=False).mean().astype('int')
  x4[name] = df4[name]['len']
  y4[name] = df4[name][name]
  plt.plot(x4[name], y4[name], label=name)

plt.legend()

df.sort_values("len", ascending=False).head(20)

df2.sort_values(["len", "all"]).head(200)